### ISSUE TITLE
PR description is removed every time commit is amended

### ISSUE THREAD

**Issue by DougSig** [pingpongboss/git-multi-pr#100]
Right now I have to rewrite my PR description each time I `git-multi-pr export`.

**Comment by DougSig** [comment]
I like to attach screenshots to my PR description, so i'd need to copy and paste the github link that gets generated after I attach the file.

**Comment by pingpongboss** [comment]
I've got a workaround for this as well. git-multi uses the first comment to :lock: the PR. Just edit that and add/embed your screenshot. 

When you re-export, it won't get overwritten.
