### ISSUE TITLE
No check that ok.sh is executable

### ISSUE THREAD

**Issue by marcandre** [pingpongboss/git-multi-pr#130]
Would be nice to have in `status`

**Comment by pingpongboss** [comment]
Wanna take a stab at this? :)

**Comment by marcandre** [comment]
I'm afraid the shell is not my forte, I use Ruby instead...
Feel free to close; most users probably follow your install instructions as is. I can't (my dotfiles are under source management).

**Comment by pingpongboss** [comment]
Heh, no worries, I'll look into it.
